const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map();function node(){return {dataset:{},style:{},textContent:'',title:'',children:[],append(e){this.children.push(e)},replaceChildren(...a){this.children=a}}}
const context={document:{getElementById(id){if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},createElement:node},Date,innerWidth:1920,innerHeight:1080,addEventListener(){},setTimeout(){},setInterval(){},fetch:async()=>{throw Error('test disconnect')},Image:class{}};
vm.createContext(context);vm.runInContext(fs.readFileSync('src/versus/overlay/overlay.js','utf8'),context);
const state={status:'thinking',completed:3,total:32,match:{id:3,entrants:['A'.repeat(120),'Red model'],parties:['balanced','vanguard'],map:'woodland',objective:'either',opener:1},observation:{round:5,sequence:20,active_seat:1},thinking_seat:1,decisions:[{rationale:'Blue decision',round:4,sequence:18},{rationale:'Long rationale '.repeat(100),round:5,sequence:20}],standings:Array.from({length:12},(_,i)=>({id:'Model '+i,wins:i,draws:0,losses:1,points:i*3}))};
context.render(state);assert.equal(nodes.get('red-thinking').textContent,'THINKING');assert.equal(nodes.get('blue-thinking').textContent,'');assert.equal(nodes.get('red').dataset.active,'true');assert.equal(nodes.get('standings').children.length,4);assert.equal(nodes.get('red-decision').title,state.decisions[1].rationale);assert.match(nodes.get('objective').textContent,/CASTLE/);
context.render({...state,status:'complete',last_result:{outcome:3,entrants:['A','B'],victory_reason:'round_limit'}});assert.equal(nodes.get('red-thinking').textContent,'');assert.match(nodes.get('result').textContent,/Draw/);
context.render({...state,status:'waiting',decisions:[null,null],observation:null});assert.equal(nodes.get('blue-decision').textContent,'Waiting for Blue');assert.equal(nodes.get('red').dataset.active,'false');assert.equal(nodes.get('phase').textContent,'');
console.log('PASS overlay waiting, thinking, complete, draw, long rationale and 12-entrant paging');
